language: cpp

compiler: gcc

dist: bionic

addons:
    apt:
        packages:
            - python3
            - python3-setuptools
            - python3-pip

before_install:
    - pip3 install setuptools
    - pip3 install online-judge-tools

script:
    - bash ./test/test.sh